services:
  backend:
    image: node:20
    container_name: backend
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate reset --force &&
             npx tsx prisma/seed.ts &&
             npm run build &&
             npm run start"
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - hvacnet

  frontend:
    image: node:20-alpine
    container_name: frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - hvacnet

  db:
    image: postgres:16
    container_name: hvac-db
    restart: always
    environment:
      POSTGRES_USER: hvac_user
      POSTGRES_PASSWORD: hvac_pass
      POSTGRES_DB: hvac_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hvac_user -d hvac_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hvacnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
        - prometheus_config:/etc/prometheus:ro
        - prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--storage.tsdb.retention.time=15d'
    ports:
        - "9090:9090"
    networks:
        - hvacnet
    depends_on:
        backend:
            condition: service_started
        prometheus-config-init:
            condition: service_completed_successfully

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - hvacnet

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./monitoring/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - hvacnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
      - loki
    networks:
      - hvacnet

  prometheus-config-init:
    image: alpine:latest
    env_file:
        - ./monitoring/.env
    volumes:
        - ./monitoring/prometheus.yml:/template/prometheus.yml:ro
        - prometheus_config:/output
    command: sh -c "apk add --no-cache gettext && envsubst < /template/prometheus.yml > /output/prometheus.yml"

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
        - "9100:9100"
    networks:
        - hvacnet

volumes:
  pgdata:
  prometheus_data:
  prometheus_config:
  loki_data:
  grafana_data:

networks:
  hvacnet:
    driver: bridge
